### ISSUE TITLE
Any more info on firmware upload?

### ISSUE THREAD

**Issue by pfalcon** [stormluke/Mili-iOS#1]
From https://github.com/stormluke/Mili-iOS/wiki/Characteristics#firmware-data :

> Firmware Data TODO

I wonder, if any new info is available since wiki was last edited? (Just to make sure I won't duplicate work somebody else might have done.) Thanks.

**Comment by stormluke** [comment]
Sorry, I no longer work on this so there is no more info. Thank you for your attention.

**Comment by pfalcon** [comment]
Thanks for response.
