### ISSUE TITLE
能不能做个打呼时震动手环的程序

### ISSUE THREAD

**Issue by entron** [stormluke/Mili-iOS#2]
用手机检测打呼的声音，如果检测到打呼或者是[呼吸暂停](http://zh.wikipedia.org/wiki/%E7%9D%A1%E7%9C%A0%E5%91%BC%E5%90%B8%E6%9A%82%E5%81%9C)，就震动手环。

**Comment by stormluke** [comment]
~~越狱前的 iOS 似乎不能在后台处理声音输入 ╮(─▽─)╭~~

抱歉查了下是可以的

**Comment by entron** [comment]
应该会有很多人喜欢这个功能。
